### ISSUE TITLE
Easy suggestion to fit skimr output as 1 line per var , (without line "wrap-around")

### ISSUE THREAD

**Issue by sfd99** [ropenscilabs/skimr#113]
**_Hi Elinw -_** 
     **skimr** working great! (Rstudio / Ubuntu Linux 32 bits).

An _easy to implement suggestion_
to save precious screen real estate
and make the **skimr** output 
more readable in smaller screens.

In the top title line of **skim**,
please shorten the names of some of the title text...

_Specifically:_
  -  `25% quantile`   to simply:  `Q1`
  -  `75% quantile`   to simply:  `Q3`
  -   `missing`   to simply:   `miss` (or `NA`)
  -   `complete`  to simply:  `compl.`

Just these 4 easy text changes,
will avoid the "wrap around" of each variable line
in smaller monitor screens.
  _= much easier to read (every var is contained in one line...)._

Values _for each var_ 
will then fit _much better_ within a single screen line...

**Thanks Elinw  :-)
Really appreciate your effort!**

**Comment by elinw** [comment]
Not just me!  Let's get thoughts from other people.

**Comment by earino** [comment]
This all feels reasonable. Is the right answer something like "if we have the screen real estate use the long names, if we don't use the short names?"

**Comment by sfd99** [comment]
@earino Yes - Good suggestion!
And a leap in usability.

Some titles are 10+ characters long,
yet the values under the column
are only 1 or digits... ie: 
Col Title:  "missing"
Value:       0 

Personally, i prefer 
the abbreviated column titles
all the time, always.
(= easier to read each horizontal variable line).

**Comment by elinw** [comment]
Would you rather say Q1 or P25?  I think Q1.
I think NA would be consistent with some other summaries I have seen in R.

**Comment by sfd99** [comment]
@elinw Yes! **Q1**,  **Q3**
                 ....instead of the current longer column headers ...

**Comment by elinw** [comment]
@AmeliaMN Do you have opinions about this and specifically what shorter labels would make sense for beginning stats students?

**Comment by elinw** [comment]
So that PR is a concept ... it makes a more compact layout and uses the screen space better.

**Comment by rsangole** [comment]
I second (or third) the motion for this. Will save screen space, especially when working on laptops.

**Comment by elinw** [comment]
ropenscilabs/skimr#117 

![screen shot 2017-06-21 at 8 02 47 pm](https://user-images.githubusercontent.com/754813/27411627-d7755a16-56bc-11e7-9195-36cf8aa35c04.png)

**Comment by elinw** [comment]
I think comp is not a good abbreviation, at least to me I don't know what it means. 
@sfd99 @earino

**Comment by sfd99** [comment]
baybe...
  complete = **! NA** 
or 
  complete =  **noNAs**

**Comment by elinw** [comment]
@michaelquinn32 and I were discussing this and I think we're both worried that using Q would be confusing (is it Quarter, Quartile, Quantile etc).  It could also create some other problems as the code is now, but there is probably a better way to do it that leaves the column title alone yet allows the display to be different. .  Anyway in the meantime also take a look at how much smaller the lines are when we control the number of decimal places!

![screen shot 2017-07-16 at 4 21 17 pm](https://user-images.githubusercontent.com/754813/28254035-2863f270-6a77-11e7-95dd-96a3aeba9096.png)
(on a mac book).

**Comment by earino** [comment]
Yeah that seems pretty great. Does it do the smart thing when all the numbers are like 0.000x. I think I'm asking if it autoexpands when needed for precision).

**Comment by elinw** [comment]
I think that "skim" is really about getting an overview and the print is about getting an appropriate display, but the way that function works is that it adjusts to the underlying data.  This is discussed more in the sig figs issue.  This has no impact on the stored values in the skim_df object which is what you would be using for any calculations.

**Comment by elinw** [comment]
I'm going to close this because it's really a lot better in the develop branch and in some other pull requests.
