### ISSUE TITLE
latex output

### ISSUE THREAD

**Issue by ak-koli** [ropenscilabs/skimr#123]
in latex output "hist" is coming as boxes, screen-shots of output

**Comment by elinw** [comment]
Yes, same issue but worse for me.  
I tried adding

```
    pdf_document:    
    latex_engine: xelatex

```
to my yaml and that seemed to help.
It's interesting that you got boxes,  for me it would not knit and I got

> ! Package inputenc Error: Unicode char ▂ (U+2582)
> (inputenc)                not set up for use with LaTeX.
> 
> See the inputenc package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.280 \end{verbatim}
> 
> Try running pandoc with --latex-engine=xelatex.
> pandoc: Error producing PDF
> Error: pandoc document conversion failed with error 43
> Execution halted

**Comment by ak-koli** [comment]
What do you suggest now?

**Comment by elinw** [comment]
Did you try adding that line to your yaml? What happened?

**Comment by elinw** [comment]
Also is it rendering okay in the console? Are you on  Windows?

**Comment by ak-koli** [comment]
I'm using Linux  Mint.

**Comment by ak-koli** [comment]
In which file (index; _output, or _bookdown) I should add these lines
```
pdf_document:    
    latex_engine: xelatex
```

**Comment by ak-koli** [comment]
The html and console output is coming only issue with latex output. Even without adding your suggested lines, RStudio now showing error:

`Latexmk, John Collins, 1 January 2015. Version 4.41
! Package inputenc Error: Unicode char ▇ (U+2587)
(inputenc)                not set up for use with LaTeX.

Error: Failed to compile thesis-ajay.tex. See thesis-ajay.log for more info.
In addition: Warning message:
Your latexmk version seems to be too low. You may need to update the latexmk package or your LaTeX distribution. 
Please delete thesis-ajay.Rmd after you finish debugging the error.
Execution halted

Exited with status 1.`

**Comment by elinw** [comment]
`latexmk version seems to be too low`

DId you check that?  THe problem is the character encoding ... also what encoding are you using?

**Comment by ak-koli** [comment]
I'm not sure but it seems

==> rmarkdown::render_site(encoding = 'UTF-8')

**Comment by elinw** [comment]
So Windows was having a problem in the console and quoting from the readme that was updated after we looked at that:

> 
> Windows support for spark histograms
> 
> Windows cannot print the spark-histogram characters when printing a data-frame. For example, "▂▅▇" is printed as "<U+2582><U+2585><U+2587>". This longstanding problem originates in the low-level code for printing dataframes. One workaround for showing these characters in Windows is to set the CTYPE part of your locale to Chinese/Japanese/Korean with Sys.setlocale("LC_CTYPE", "Chinese"). These values do show up by default when printing a data-frame created by skim() as a list (as.list()) or as a matrix (as.matrix()).

So you could consider experimenting with the locale.  There are more details in the closed issue about that.

**Comment by ak-koli** [comment]
Please help me, where should I write your suggested lines:

```
pdf_document:    
    latex_engine: xelatex
```

**Comment by elinw** [comment]
You should have a YAML file ... and it goes in the top section between the two lines.
[R markown cheat sheet](https://www.rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf
)

**Comment by ak-koli** [comment]
Thank you. I'm using bookdown. So, there are many files. If I'm not wrong, you are referring about the index.Rmd file.

**Comment by elinw** [comment]
Yes that's right. I'm not sure exactly how it will be but in a file I have I have:

```
output:
  bookdown::pdf_book:
    includes:
      in_header: style.css

```

So probably right under the line that says bookdown::

**Comment by ak-koli** [comment]
Still the same issue, the pdf output is printing "boxes" for "hist" option.

**Comment by elinw** [comment]
Well it's basically a LaTex issue rendering that character so either it needs a different engine or a different encoding.  I'm not sure what to suggest other than trying the other options for engines.

**Comment by ak-koli** [comment]
Thank you, in case, you find some solution please post it here too.

**Comment by elinw** [comment]
@ak-koli  One issue maybe that you want to read the discussion here : https://github.com/ropenscilabs/skimr/issues/136

**Comment by lnalborczyk** [comment]
Hi, I have the same issue, i.e., histograms are outputted output as empty boxes. Below, a screenshot from the .pdf file knitted from the template "getting ready for fonts", using the Arial Font.

<img width="797" alt="screenshot 2019-01-11 at 13 45 13" src="https://user-images.githubusercontent.com/10812999/51034491-3a19c580-15a7-11e9-8dad-c5f8174d2ba9.png">

Any tip to solve this problem ? I am working on macOS mojave version 10.14, rstudio 1.1.456, R 3.5.0, skimr 1.0.3.
