### ISSUE TITLE
Option to spark-histograms = FALSE

### ISSUE THREAD

**Issue by Fredo-XVII** [ropenscilabs/skimr#130]
Hello,

I love the layout of the skimr output.  I have totally replaced the use of the summary function with skim().  With that said, knowing that the spark-histograms don't generate properly in Windows, is there any way to add an option to make it FALSE so that it does not print out.  That would be great, and I think it would go faster.  I am an R user not an R programmer, otherwise, I would submitted a pull request :).

Thank you,

Alfredo

**Comment by elinw** [comment]
`skim_with()`  allows you to specify which specific statistics you want to use.  For example
`skim_with(numeric = list(hist = NULL))`  will do what you want by setting the hist statistic to NULL.

**Comment by Fredo-XVII** [comment]
Awesome, thank you!! I tried to find it on skimr website, but it wasn't listed as an example.
