### ISSUE TITLE
support for time-based variables planned?

### ISSUE THREAD

**Issue by randomgambit** [ropenscilabs/skimr#132]
Hello there,

thanks for this promising package. I wonder if you plan to add support for time based variables such as dates, timestamps, etc. The same way `Pandas` does it: that is showing minimum/maximum date, frequency, etc.

That would be extremely useful!
Thanks!

**Comment by elinw** [comment]
Have you tried using time variables in skimr? We do have support for Date and POSIXct classes. The formatting of these in the print method is updated in the develop branch. We haven't dealt at all with time without dates.  I think there's a basic question of what classes to add support for but if there is a specific other time related class that is widely used it would make sense.  In the meantime it is very easy to add support for your own class using skim_with(). 

https://github.com/ropenscilabs/skimr/blob/master/R/defaults.R#L55
https://github.com/ropenscilabs/skimr/blob/master/R/defaults.R#L81
https://github.com/ropenscilabs/skimr/blob/master/R/functions.R#L11

**Comment by randomgambit** [comment]
@elinw thanks! very useful. When do you plan to release this in the master branch? btw, you should have a look at `hms`, which deals with time variables (without dates). it is part of the tidyverse and I think it would be a useful class to add. What do you think?

**Comment by elinw** [comment]
I'm really not sure on timing, it's a group project. I  really need people to install and give feedback on the develop branch.  In the meantime `hms` would be great and we'd welcome a contribution of that if you want to create it (just follow the pattern of the other classes).   I don't mind adding that dependency because it is a small package and even already has the formatting/rounding issues handled.

**Comment by elinw** [comment]
I'm going to make this a "good first issue." If you would like to take it on, please look at how the functions for a class are created in the develop branch.  Then just do the same kind of thing for hms variables.   You can just do a few basic statistics to start.

**Comment by randomgambit** [comment]
Hello there! just an update, it seems `skimr` does not support timestamps unfortunately.


```
library(skimr)
library(dplyr)
library(lubridate)

skim(data_frame(time = ymd_hms('2018-01-01 12:12:12', '2018-01-01 12:12:13')))

> skim(data_frame(time = ymd_hms('2018-01-01 12:12:12', '2018-01-01 12:12:13')))
Skim summary statistics
 n obs: 2 
 n variables: 1 

Variable type: POSIXct 
 variable missing complete n        min        max     median n_unique
     time       0        2 2 2018-01-01 2018-01-01 2018-01-01        2
```

Is that expected? Here of course the min/max are wrong.

Thanks!

**Comment by elinw** [comment]
You can actually create your own statistics for specific classes and your
own. If you want to create formatting that includes the   There are
basically an unlimited number of data classes.  ymd_hms is class POSIXct
according to the documentation so it is getting the same treatment as other
data with the same class. You could override this.

I don't think I would say that min and max are wrong, they just don't
display the hms parts.

**Comment by elinw** [comment]
posixct = list(format = "%Y-%m-%d")
Is how it is formatted now, you could override that with `skim_formats` adding the hms parts.

**Comment by randomgambit** [comment]
@elinw thanks! that is good to know!
