### ISSUE TITLE
Re-installed skimr but loading skimr gives an error message

### ISSUE THREAD

**Issue by sfd99** [ropenscilabs/skimr#149]
as per GIT page of skimr package,
installed in latest Rstudio with:

devtools::install_github("hadley/pillar")
devtools::install_github("ropenscilabs/skimr")

Installation seemed to go fine,
although the skimr version is shown as:  **0.9000**
(I use to have a working version of skimr **1.0** before...strange!).
 
But then, 
after loading the "pillar" pkg,
I try to load the skimr pkg in Rstudio,
(click the checkbox of skimr in the Packages tab),
and get _this_ error:

> library("skimr", lib.loc="~/R/i686-pc-linux-gnu-library/3.4")
Error: package or namespace load failed for ‘skimr’ in get(method, envir = home):
 lazy-load database '/home/ray/R/i686-pc-linux-gnu-library/3.4/skimr/R/skimr.rdb' is corrupt
In addition: Warning messages:
1: In .registerS3method(fin[i, 1], fin[i, 2], fin[i, 3], fin[i, 4],  :
  restarting interrupted promise evaluation
2: In get(method, envir = home) :
  restarting interrupted promise evaluation
3: In get(method, envir = home) : internal error -3 in R_decompress1
> 
_Wow!_
I don't  even know what this error means
or how to fix it...

If I simply do:
   library("skimr")
I get the same error message as above.

skimr **v 1.0** used to work _fine_ before
in this same PC, same Rstudio, same OS (Linux Ubuntu 14.04 32-bit).
**My current R version: 3.4.2**

Is skimr version **0.9000** the latest?
I had version 1.0 before...

Help!

**Comment by elinw** [comment]
Yes we realized that with a version number of 1.0 people thought it was a released version so we pulled it back to .9. 
Please try cleaning out your environment with the broom button, then restarting R (you can try this in the Session drop down.    if that doesn't work, exit RStudio and re-enter. I've gotten that message before when updating different packages.   
Let me know what happens if you try that.

**Comment by sfd99** [comment]
Thank you, Elin!
Followed your instructions,
and skimr works fine, again! :-)
