### ISSUE TITLE
How to you get skimr to show shorter column names (to fit a small laptop screen)

### ISSUE THREAD

**Issue by sfd99** [ropenscilabs/skimr#159]
**_Hi Elin,_**
Great job!

**Q:**
I have the latest **skimr** pkg version: **0.9000**

**skim(chickwts)**
I get _these_ column names:
    ...**`25% quantile`**  median  **`75% quantile`** ...etc.

But... in _your_ equivalent GitHub page example,
you get these much _shorter_ column names:
    ... **p25**   median   **p75** ... etc.

I prefer the latter, much shorter column names,
(they fit better in a smaller laptop screen...).

How exactly do you get skimr 
to display these much shorter column names?:
   **p25**  (instead of the longer: _`25% quantile`_) and
   **p75**  (instead of the longer: _`75% quantile`_). ?

Thanks, Elin!
**SFd99**

**Comment by elinw** [comment]
Hi,
Sounds like you may need to update to the current version, we incorporated those names about 2 days ago.  

To update, you should use `devtools::install_github("ropenscilabs/skimr")`.

**Comment by elinw** [comment]
I'm going to close now, since those changes are in the new version.  We can open an new issue if needed.
