### ISSUE TITLE
Future request: Output in R markdown

### ISSUE THREAD

**Issue by elben10** [ropenscilabs/skimr#165]
It would be great if there was a function, which allowed one to use skimr smoothly in R markdown. I've written the following code, which does the job, but it can most definitely be coded much better. Thanks for a nice package

``` r
library(dplyr, warn.conflicts = FALSE)
library(knitr, warn.conflicts = FALSE)
library(purrr, warn.conflicts = FALSE)
library(skimr, warn.conflicts = FALSE)
library(tidyr, warn.conflicts = FALSE)
df <- tibble(numeric_ = sample(1:10, 100, TRUE),
                 character_ = sample(who$country, 100, TRUE),
                 factor_ = factor(sample(LETTERS[1:3], 100, TRUE), labels = paste("f", 1:3, sep = "_")))
df %>%
  skim() %>%
  select(var, type, stat, formatted) %>%
  filter(type == "character") %>%
  spread(stat, formatted) %>%
  knitr::kable()
```

| var         | type      | complete | empty | max | min | missing | n   | n\_unique |
|:------------|:----------|:---------|:------|:----|:----|:--------|:----|:----------|
| character\_ | character | 100      | 0     | 41  | 4   | 0       | 100 | 78        |

``` r
df %>%
  skim() %>%
  select(var, type, stat, formatted) %>%
  filter(type %in% c("double", "integer")) %>%
  spread(stat, formatted) %>%
  select(var, type, missing, complete, n, mean, sd, min, p25, median, p75, max, hist) %>%
  knitr::kable()
```

| var       | type    | missing | complete | n   | mean | sd  | min | p25  | median | p75 | max | hist     |
|:----------|:--------|:--------|:---------|:----|:-----|:----|:----|:-----|:-------|:----|:----|:---------|
| numeric\_ | integer | 0       | 100      | 100 | 5.74 | 2.9 | 1   | 3.75 | 6      | 8   | 10  | ▇▂▅▅▁▅▇▇ |

``` r
df %>%
  skim() %>%
  select(-level, -value) %>%
  filter(type %in% c("factor")) %>%
  nest(-var, -type, -stat) %>%
  mutate(formatted = map_chr(data, function(x) stringr::str_c(flatten(x), collapse = " "))) %>%
  select(-data) %>%
  spread(stat, formatted) %>%
  knitr::kable()
```

| var      | type   | complete | missing | n   | n\_unique | ordered | top\_counts                      |
|:---------|:-------|:---------|:--------|:----|:----------|:--------|:---------------------------------|
| factor\_ | factor | 100      | 0       | 100 | 3         | FALSE   | f\_1: 40 f\_2: 31 f\_3: 29 NA: 0 |

**Comment by elinw** [comment]
Can you define what you mean by "use smoothly"?  There are a lot of issues with converting to documents of different types (html, pdf, Word, Open Office).  I think they are the majority of the open issues at this point.

**Comment by elben10** [comment]
What I mean about smoothly is just, that it would be very nice if it was possible to create a function that allowed fast table output to different types of output (Especially html and latex). I guess one option would be using kable from knitr, and extending it by adding a skim_df method, and I was thinking about one of the following syntaxes (Beneath). Another solution would be to create a separate function, which provided the same functionality when used in a Rmd document. Does it make sense?

```r
df %>%
   skim_kable(type, ...) #(...) is passed to knitr::kable()
``` 

or 

```r
df %>%
   skim_kable(type) %>%
   kable()
```

**Comment by elinw** [comment]
That's an interesting concept. But what if someone prefers to use pander?  So I guess we could make a convenience function that does that.   I think I look at the fact that kable(print.skim_df(df)) doesn't work as expected as a bug that it would be good to solve.

**Comment by elinw** [comment]
@michaelquinn32 started a branch that will make using kable, pander etc possible. https://github.com/ropenscilabs/skimr/pull/170

**Comment by elinw** [comment]
I've merged the pull request for kable support into develop so I am closing this issue.
