### ISSUE TITLE
error when using dplyr::arrange() on skim output

### ISSUE THREAD

**Issue by jrosen48** [ropenscilabs/skimr#171]
Hi, thanks for a great package!

The `dplyr` function `filter()` (operating on the output of `skim`) works fine, but `arrange()` does not seem to work:

``` r
library(skimr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
skim(mtcars) %>% filter(stat=="hist")
#> # A tibble: 11 x 5
#>      var    type  stat      level value
#>    <chr>   <chr> <chr>      <chr> <dbl>
#>  1   mpg numeric  hist ▂▅▇▇▇▃▁▁▂▂     0
#>  2   cyl numeric  hist ▆▁▁▁▃▁▁▁▁▇     0
#>  3  disp numeric  hist ▇▇▅▁▁▇▃▂▁▃     0
#>  4    hp numeric  hist ▆▆▇▂▇▂▃▁▁▁     0
#>  5  drat numeric  hist ▃▇▂▂▃▆▅▁▁▁     0
#>  6    wt numeric  hist ▂▂▂▂▇▆▁▁▁▂     0
#>  7  qsec numeric  hist ▂▃▇▇▇▅▅▁▁▁     0
#>  8    vs numeric  hist ▇▁▁▁▁▁▁▁▁▆     0
#>  9    am numeric  hist ▇▁▁▁▁▁▁▁▁▆     0
#> 10  gear numeric  hist ▇▁▁▁▆▁▁▁▁▂     0
#> 11  carb numeric  hist ▆▇▂▁▇▁▁▁▁▁     0
skim(mtcars) %>% arrange(mean)
#> Error in arrange_impl(.data, dots): cannot arrange column of class 'function' at position 1
```

*Should* arrange work here? Am I using this correctly / is there a work-around? Thank you!

**Comment by elinw** [comment]
Doesn't arrange take a column name?  The only columns in the skim object are var, type, stat, level and value.   
I think there is a lot of confusion between the skim_df object (which is long) and the printed version, which is wide.   This is something we are thinking about.  My sense is people really want access to those wide data frames.

**Comment by jrosen48** [comment]
Ah, thank you! I didn't understand the difference between the skim_df object and the output of the print method. I would agree that access to those wide data frames would be useful!

**Comment by elinw** [comment]
@jrosen48 Would you mind posting that as a request in a new issue?

**Comment by jrosen48** [comment]
Sure thing!

On Wed, Oct 25, 2017 at 4:23 PM elinw <notifications@github.com> wrote:

> @jrosen48
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jrosen48&d=DwMCaQ&c=nE__W8dFE-shTxStwXtp0A&r=K686QAY7eaZdPEFBr8PPgs7NJEd4IX1trEl5UE4sKWQ&m=TSqjLXhOGKFt8g_206ohpJMnHXaFwCtfte2LoWaVV3A&s=I4khQvLIQOHUxZZCG_ZC6Pp02lr8oK9cfqtaY2hHAvk&e=>
> Would you mind posting that as a request in a new issue?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ropenscilabs_skimr_issues_171-23issuecomment-2D339459280&d=DwMCaQ&c=nE__W8dFE-shTxStwXtp0A&r=K686QAY7eaZdPEFBr8PPgs7NJEd4IX1trEl5UE4sKWQ&m=TSqjLXhOGKFt8g_206ohpJMnHXaFwCtfte2LoWaVV3A&s=JqgM8o800D1Fa0ZXO0MjEVmmhE554otHbDlEiyDb3Bg&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEYh9t5sRzhy3Y5q-5FAmlVQqNwvX-5FPZKXks5sv5imgaJpZM4QE2QC&d=DwMCaQ&c=nE__W8dFE-shTxStwXtp0A&r=K686QAY7eaZdPEFBr8PPgs7NJEd4IX1trEl5UE4sKWQ&m=TSqjLXhOGKFt8g_206ohpJMnHXaFwCtfte2LoWaVV3A&s=RqZ6qvN1kLqxi9EZw5lBhdi4Sx0AFT5kp-XJ6YpQQYM&e=>
> .
>
-- 
Joshua Rosenberg, Ph.D. Candidate
Educational Psychology ​&​ Educational Technology
Michigan State University
https://urldefense.proofpoint.com/v2/url?u=http-3A__jmichaelrosenberg.com&d=DwIFaQ&c=nE__W8dFE-shTxStwXtp0A&r=Q73Qkke4ZYIE4BW-ngDz7ODor5W-k3bMwPvsMqn6oanMP5SRCSpkrFk4avGxTWPTdn92HVF6ZS7hR9LFv--GekkzLB5bX-qjDWvsO-i8eQYDd7DbZnSOe7eUmaSrfhDtt1_lQYuKvbc_Yc9Mlb29zQ&m=s7YdqtsAykv9aeS9HDoNvIdlHZNLCffLi_picPAfhLg&s=9bZv39h7Qkbw6Q1ZRE-wuzrVCIVKO3F3dXm1oZlQ6f8&e=
