### ISSUE TITLE
skim_print not working

### ISSUE THREAD

**Issue by jorgesinval** [ropenscilabs/skimr#172]
What happened to the `skim_print`? I had this code to produce a nice table (with some added extra stats using the `skim_with` function) since the last version it isn't working. Which function did replace `skim_print`? If none, how can I recover the last one with `skim_print`?

```
df %>%
  skim() %>% 
  filter(stat %in% c("n", "mean", "sd", "min", "max", "sk", "ku", "hist", "% missing")) %>%
  skim_print %>%
  knitr::kable(digits=2, caption = 'Descriptives with histogram')
```

**Comment by elinw** [comment]
Oh I think it is now  internal you may need to use  :::  instead of  ::

**Comment by jorgesinval** [comment]
Nice, but how can it test this pull request?
The skimr:::skim_print is found, but it isn't working as it was in the past, now it displays the following message:

`Error in collapse_levels(.data, groups) : argument "groups" is missing, with no default`

Any help would be appreciated.

**Comment by elinw** [comment]
For your function use the master branch. There are some substantial changes to printing in the new branch and I think your function will change (or not be needed when the branch is ready to commit.
If you updated your copy of the repo I find that I have to always empty the environment and build and reload the package.   I've gotten that exact message before.

**Comment by jorgesinval** [comment]
It worked well with the 0.9000 version, but with this last one (0.9100) it isn't working. How can I install the previous one?

**Comment by elinw** [comment]
Well if you are in using git you can go back to that commit. 

So it's a bit confusing going back and forth, but  what I *think* you could do is
- install the print_engines branch
- use results = "asis" in the chunk options
- use e.g. skim(iris) %>% skimr:::kable(format = "html")

From ?kable the format options are : latex, html, markdown, pandoc, and rst.

**Comment by jorgesinval** [comment]
Well, I don't know how to install an older branch using Rstudio...
If I try your code with the chunk option I get this error:
`Error: 'spark_bar' is not an exported object from 'namespace:pillar'`

Well, I just want to obtain a table as I did before, with the stats in the columns and the variables in the rows, and also with some extra stats that I added using `skim_with`. Even if I have to change my code, I won't mind.

**Comment by tiernanmartin** [comment]
I am also experiencing this error message.

**Comment by elinw** [comment]
Update to the current build, that issue was fixed earlier today on the master branch. 


@jorgesinval  I just realized though that I didn't update the print_engine branch.

**Comment by elinw** [comment]
Okay the not exported message should be gone in all three branches (master, develop, print_engines).

**Comment by tiernanmartin** [comment]
Now working for me 👍 

Thanks for the <3min. response time @elinw!

**Comment by elinw** [comment]
@jorgesinval   you can always do skim_with() to get the extra stats/remove ones you don't want.  THen take the skim object and use filter to select a type, then tidyr to make the wide table.  Our complication is that we are trying to do that for all of them at once and then allow users to use kable() or pander().

**Comment by jorgesinval** [comment]
Thanks @elinw ! In the past it was working, I was able to add stats and make a table with the functions added through `skim_with` and with those that you have in the package, but that was in the v. 0.9000. Now the same code:

```
df %>%
  skim() %>% 
  filter(stat %in% c("n", "mean", "sd", "min", "max", "sk", "ku", "hist", "% missing")) %>%
  skimr:::skim_print() %>%
  knitr::kable(digits=2, caption = 'Descriptives with histogram')

```
produces this error:

```
Error in collapse_levels(.data, groups) : 
  argument "groups" is missing, with no default
```

**Comment by elinw** [comment]
Okay I have seen that error message before.  Since I am usually using a development version it may be a little different than if you are using install_github, but one thing I'd like you to try is clearing your environment.  That often seems to solve issues for me.  In this case since your data is not grouped, groups should be NULL so one possibility as a temporary fix would be to add `groups =NULL` to the print function.     I'm assuming that the skim object coming into skim_print is fine.  Basically one of the main changes in .91 is adding support for grouped data and since skim_print is now internal it assumes that the preprocessing related to that has been handled in the exported functions.

**Comment by elinw** [comment]
I'm going to close this and ask for a new issue in light of the newer code.
