### ISSUE TITLE
skim does not have a matrix method

### ISSUE THREAD

**Issue by ggrothendieck** [ropenscilabs/skimr#217]
Below we convert the built-in `BOD` to a matrix and then run `skim`.  Expectation was that it would give the same result as `skim(BOD)`.

```
> skim(as.matrix(BOD))
No skim method exists for class matrix.
```

**Comment by elinw** [comment]
Correct.  However you can create a matrix method following the instructions in the vignette.  One of the things I've thought about is what a skim of a matrix be.  You're suggesting that a matrix be treated as though it was a data frame where all of the variables are of the same type as the matrix. (This is effectively what the core summary() does.)
```
summary.matrix
function (object, ...) 
{
    summary.data.frame(as.data.frame.matrix(object), ...)
}
```

  But that's not always how matrices should work.  For example take `euro.cross` which is stored as a matrix.  `colMeans()` and `rowMeans()` and `mean()` are all different and what do they mean anyway?  Other times a matrix is definitely similar in design to a data frame.  

We are also not currently supporting tables or cubes, both of which are found in the datasets package.  I'm also not sure what I would do with those.

**Comment by elinw** [comment]
https://github.com/ropenscilabs/skimr/blob/master/vignettes/Using_skimr.Rmd

I documented this in the vignette.
