### ISSUE TITLE
skimr depends on stringr >= 1.1.0

### ISSUE THREAD

**Issue by jarodmeng** [ropenscilabs/skimr#218]
`str_split` only gained an `simplify` argument since v1.1.0. [This line](https://github.com/ropenscilabs/skimr/blob/cf47c2a6142fd0320b8564cd3913038b2f838eca/R/skim_print.R#L217) uses the `simplify` argument, so it means that `skimr` depends on `stringr` >= 1.1.0.

**Comment by elinw** [comment]
Thanks!

**Comment by elinw** [comment]
#219

**Comment by michaelquinn32** [comment]
Thanks Jarod!
