### ISSUE TITLE
skim fails when numeric variable is all missing

### ISSUE THREAD

**Issue by rgayler** [ropenscilabs/skimr#221]
I was reading a SAS data file with haven and trying to skim the data frame. skim() failed with error message:
`Error in if (all(x == 0)) x <- x + 1: missing value where TRUE/FALSE needed`

I tracked this down to a numeric variable with all values missing.

```
library(skimr)
library(tidyverse)
#> ── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
#> ✔ ggplot2 2.2.1.9000     ✔ purrr   0.2.4     
#> ✔ tibble  1.4.1          ✔ dplyr   0.7.4     
#> ✔ tidyr   0.7.2          ✔ stringr 1.2.0     
#> ✔ readr   1.1.1          ✔ forcats 0.2.0
#> ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
#> ✖ dplyr::contains()    masks skimr::contains()
#> ✖ dplyr::ends_with()   masks skimr::ends_with()
#> ✖ dplyr::everything()  masks skimr::everything()
#> ✖ dplyr::filter()      masks stats::filter()
#> ✖ dplyr::lag()         masks stats::lag()
#> ✖ dplyr::matches()     masks skimr::matches()
#> ✖ dplyr::num_range()   masks skimr::num_range()
#> ✖ dplyr::one_of()      masks skimr::one_of()
#> ✖ dplyr::starts_with() masks skimr::starts_with()

d <- tribble(~num, ~char, ~all_miss, 1, "a", NA, 2, "b", NA, 3, "c", NA)

glimpse(d)
#> Observations: 3
#> Variables: 3
#> $ num      <dbl> 1, 2, 3
#> $ char     <chr> "a", "b", "c"
#> $ all_miss <lgl> NA, NA, NA

skim(d)
#> Skim summary statistics
#>  n obs: 3 
#>  n variables: 3 
#> 
#> Variable type: character 
#>   variable missing complete n min max empty n_unique
#> 1     char       0        3 3   1   1     0        3
#> 
#> Variable type: logical 
#>   variable missing complete n mean count
#> 1 all_miss       3        0 3  NaN     3
#> 
#> Variable type: numeric 
#>   variable missing complete n mean sd min p25 median p75 max     hist
#> 1      num       0        3 3    2  1   1 1.5      2 2.5   3 ▇▁▁▇▁▁▁▇

d <- d %>% mutate(all_miss = all_miss + 0)

glimpse(d)
#> Observations: 3
#> Variables: 3
#> $ num      <dbl> 1, 2, 3
#> $ char     <chr> "a", "b", "c"
#> $ all_miss <dbl> NA, NA, NA

skim(d)
#> Warning in min(na.rm = TRUE, ...): no non-missing arguments to min;
#> returning Inf
#> Warning in max(na.rm = TRUE, ...): no non-missing arguments to max;
#> returning -Inf
#> Error in if (all(x == 0)) x <- x + 1: missing value where TRUE/FALSE needed
```

**Comment by elinw** [comment]
Hm ... what do you think should happen?  
```
> df$z2
[1] NA NA NA NA
> mean(df$z2, na.rm = TRUE)
[1] NaN
```
Or maybe return` NaN` for each statistic? I guess that would follow the logic of the handling for logical variables.

@michaelquinn32 Thoughts?

**Comment by rgayler** [comment]
I think it should follow the logic for summary()
```
> summary(rep(NA + 0L, 5))
#   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
#     NA      NA      NA     NaN      NA      NA       5 
```
The quantile values are all NA because they (conceptually) correspond to observations, whereas the the mean is NaN because (conceptually) we divided by zero.

BTW, this behaviour in skim is the same for doubles and integers.

> By the way I think this is a common situation ...

I agree, plus the primary use case of skimr would be to get the feel of an unfamiliar data set, so i would want it to handle everything that could be in such a data set and tell me what's there rather than die.

**Comment by elinw** [comment]
Okay here is where we are https://github.com/ropenscilabs/skimr/pull/222
The error is thrown by the histogram.  So we have fixed the histogram function.
Now, what that leaves is two warnings, one for Min and one for Max, which give `Inf` and `-Inf` and it issues warnings.
```

Warning messages:
1: In min(na.rm = TRUE, ...) :
  no non-missing arguments to min; returning Inf
2: In max(na.rm = TRUE, ...) :
  no non-missing arguments to max; returning -Inf
```
So that to me is a separate discussion. Yes summary.default handles this by setting them all to NA, but that's because it uses the quantile function not the `min()` and `max()` functions with the `na.rm` parameter set to TRUE.   We don't really want to write our own functions, so that leaves us with the question of whether to find a way to turn off the warnings.  
I'm going to create a separate issue for that.

**Comment by rgayler** [comment]
> The error is thrown by the histogram. So we have fixed the histogram
function.

Thanks for that.

> Now, what that leaves is two warnings, one for Min and one for Max, which
give Inf and -Inf and it issues warnings.
> summary.default handles this by setting them all to NA, but that's
because it uses the quantile function not the min() and max() functions
with the na.rm parameter set to TRUE.
> We don't really want to write our own functions,

Why not use quantile() instead of min() and max()?

Three arguments in favour of using quantile:
1. Conceptually - I think returning NA for min and max is what most people
would expect. Inf and -Inf are specific values that are not present in the
input vector. min and max are reducing functions that use Inf and -Inf as
their starting values to deal with the degenerate case of 0 input arguments
(for the same reason that sum() = 0 and product() = 1).
2. It would return the same values as summary(), which many people would
turn to when they want to cross-check what skim is telling them.
3. When people are using a skim_df I think they are much more likely to
test for is.na() than is.infinite(). I can see a lot of the intended skimr
audience spending an hour before they work that out.

**Comment by elinw** [comment]
I think the last point is the most interesting and important, I hadn't thought about the skim_df aspect at all.
Looking at ?quantile using 0 and 1 would definitely work and give us NA instead of Inf.  
We're trying to make a better summary so I don't necessarily want to use summary just because it is summary.  
Let's open a specific issue about max() and min().

**Comment by rgayler** [comment]
Without looking at the skimr code I had just assumed that you got the numeric: min p25 median p75 max by using quantile() to get the classic 5-number summary in one hit. Anyway ...

Is your fix to the histogram available on Github already. i.e. if I install from Github now will i get the version with the fixed histogram?

**Comment by elinw** [comment]
Right now it is in develop, so add ref= ”develop” tin install_gihub().  
I’m going to merge it to master after the tests run again.

We had a long discussion about the combined versus separate issue. You can combine them if you want, it works, but it’s less flexible if you want to drop say one of them using skim_with().    It is a little faster to do it all at once.

**Comment by elinw** [comment]
Oops no it went straight to master,

**Comment by elinw** [comment]
See #224 and #223 for continued discussion of these two issues.

**Comment by michaelquinn32** [comment]
#253 Should make the vignettes visible in the future.
