### ISSUE TITLE
Is there any plan to make it work on shiny/rmd?

### ISSUE THREAD

**Issue by happyshows** [ropenscilabs/skimr#231]
This package looks really cool, I'm wondering if it could be migrated to the htmlwidget framework so that it can be used in rmd files and shiny as well.

Thanks.

**Comment by elinw** [comment]
I think someone can do that. If you want to send a pull request I think it would be a nice contribution.

It already works with pander and kable in most cases as well as printing in the same format as in the console.

**Comment by elinw** [comment]
I think you could probably use this https://github.com/timelyportfolio/listviewer  along with skim_to_list().

**Comment by happyshows** [comment]
Hi @elinw , yes I think the console hist display is very informative, hence skim_to_list will lose a lot of info there due to additional drill down ... Is it possible to show the data in DT package?

**Comment by elinw** [comment]
I haven’t tried it in DT but as a package we are pretty focused on being Tidyverse friendly which means it is mainly focused on data frames.  I think you could easily convert the skim object to a data.table and work with it from there however. The main thing with the histograms and line charts is that they are inherently character variables so it is always going to be hard to mix them with numerics. Further for display purposes we should be aware of misleading precision in default R displays and that’s one reason we have formatted (string) values for display purposes.

**Comment by happyshows** [comment]
cool will spend some time to experiment (on DT) and reply here

**Comment by happyshows** [comment]
@elinw  I just realized you were confused by DT, it's not referring to data table, but a rstudio package built by Yihui  [linky](https://github.com/rstudio/DT)

btw, verbatimTextOutput seems to be easiest way to output the skim output

**Comment by elinw** [comment]
Oh okay! Thanks
