### ISSUE TITLE
Time for a doc fixit

### ISSUE THREAD

**Issue by michaelquinn32** [ropenscilabs/skimr#233]
?skim needs to give much more info that it currently does. Docs need cross references. Stats docs should be combined into a single file and aliased.

Also: #105

**Comment by elinw** [comment]
A good first step is probably simply to list the defaults for each type in the skim doc. Then expand to add the parameter values (e.g. na.rm=TRUE) and customizations for each (like handling of all NA and all the same value histograms).

**Comment by michaelquinn32** [comment]
#253
