### ISSUE TITLE
A more functional-programming friendly version of skim_with

### ISSUE THREAD

**Issue by rgayler** [ropenscilabs/skimr#235]
Enhancement:

If I have understood the documentation correctly, calling `skim_with` sets some global state such that all subsequent calls to `skim` use the set of custom statistics specified by the `skim_with` call until such time as the global state is reset by a call to `skim_with_defaults`.

This reliance on global state doesn't play well with functional programming style.

I suggest:

1. Allow `skim` to also accept the arguments to `skim_with` so that the user can speciify the custom statistics to be used by that call to `skim` without going via global state; and/or

1. Have a new function `mk_skim` that takes the same arguments as `skim_with` and returns a function which is `skim` with the `skim_with` arguments locally enclosed. That way, the user could create as many specialised skim functions as they like and have them interspersed throughout there code without having to precede each call to `skim` with calls to `skim_with_defaults` and `skim_with`.

**Comment by elinw** [comment]
Are you saying
`skim(iris, skim_with(list(numeric=c("var"), append=FALSE))`

but not push the replacement list to global state? 

So allow something like

```
s1 <- skim_with(list(numeric=c("var"))
s2 <- skim_with(list(numeric=c("mad"))

skim(iris, s2)

```

**Comment by rgayler** [comment]
Yes - that's effectively suggestion 1. The point there being that you might want a one-off selection of statistics, especially in a pipeline. Also, given that `skim_with` is currently used for setting the global default you might want a different name (say, `skim_stats`) unless you want to make a breaking change to `skim_with`.

So:
```
s1 <- skim_stats(list(numeric=c("var"))
s2 <- skim_stats(list(numeric=c("mad"))

stuff <- x %>% foo() %>% skim(stats = s1) %>% bar() %>% skim(s2)
```

Suggestion 2 was more aimed at use cases where you have a number of different skim definitions that you might want to re-use throughout an analysis.

```
# skim1 & skim2 are functions equivalent to skim with the stats argument baked in
skim1 <- mk_skim(stats = list(numeric=c("var")))
skim2 <- mk_skim(list(numeric=c("mad")))

skim1(iris)
skim2(mtcars)
skim1(foo)
skim2(bar)
```

**Comment by rgayler** [comment]
Yes - that's effectively suggestion 1. The point there being that you might want a one-off selection of statistics, especially in a pipeline. Also, given that `skim_with` is currently used for setting the global default you might want a different name (say, `skim_stats`) unless you want to make a breaking change to `skim_with`.

So:
```
s1 <- skim_stats(list(numeric=c("var"))
s2 <- skim_stats(list(numeric=c("mad"))

stuff <- x %>% foo() %>% skim(stats = s1) %>% bar() %>% skim(s2)
```

Suggestion 2 was more aimed at use cases where you have a number of different skim definitions that you might want to re-use throughout an analysis.

```
# skim1 & skim2 are functions equivalent to skim with the stats argument baked in
skim1 <- mk_skim(stats = list(numeric=c("var")))
skim2 <- mk_skim(list(numeric=c("mad")))

skim1(iris)
skim2(mtcars)
skim1(foo)
skim2(bar)
```

**Comment by elinw** [comment]
Well I think those approaches are better than some ideas that were discussed earlier.  I agree it's good to provide some approach like this, but it's a complex problem to solve so will probably be for a major release..

**Comment by michaelquinn32** [comment]
I also wanted to chime in and say thanks for the great ideas. It might be a little bit until we can write the code, but Elin and I are both really interested in finding ways (like this) to make skimr more flexible.

**Comment by rgayler** [comment]
My pleasure. Thanks for the great package.

**Comment by elinw** [comment]
@rgayler you might be interested in the discussion at https://github.com/ropenscilabs/skimr/issues/292

**Comment by elinw** [comment]
Going to close this since we are discussing in the other issue.
