### ISSUE TITLE
I'm not able to add an IQR with na.rm = TRUE to my list of summary functions

### ISSUE THREAD

**Issue by AndreaPi** [ropenscilabs/skimr#261]
Hi,

I've been using `skimr` with joy for a few days and I decided to modify the list of summary functions for the `numeric` class. I would like to remove `hist` and to add `IQR`. As it's currently done for the other `numeric` skimmers, I'd like `IQR` to work if there are `NA`s in my data set. However, I cannot seem to be able to do that:

```
library(skimr)

# test data frame
foo <- data.frame(x = c(1, 2, 3), y = c(1, 2, NA))

# naive attempt, not working because the default for IQR is na.rm = FALSE
skim_with(numeric = list(hist = NULL, iqr = IQR))
skim(foo)
# Error in quantile.default(as.numeric(x), c(0.25, 0.75), na.rm = na.rm,  : 
#  missing values and NaN's not allowed if 'na.rm' is FALSE

# trying to set na.rm = TRUE
skim_with_defaults()
skim_with(numeric = list(hist = NULL, iqr = IQR(na.rm = TRUE, ...)))
# Error in skim_options(..., env = "functions", append = append) : 
#  '...' used in an incorrect context

# more involved attempt
skim_with_defaults()
skim_with(numeric = list(hist = NULL, iqr = diff(quantile(c(0.25, 0.75), na.rm = FALSE, names = FALSE,  type = 7, ...))))
# Error in diff(quantile(c(0.25, 0.75), na.rm = FALSE, names = FALSE, type = 7,  : 
#  '...' used in an incorrect context
```
Is there a way I could get `IQR` to work with `skimr`, when I have `NA`s in my dataset?

**Comment by michaelquinn32** [comment]
Hi Andrea!

Functions like IQR need to be partially applied into order to have additional arguments work with skimr.

Your fix would look like this:
IQR = purrr::partial(IQR, na.rm = TRUE)

If you don't want to use purrr, try
IQR = function(x) IQR(x, na.rm = TRUE)

See more examples here:
https://github.com/ropenscilabs/skimr/blob/9280a7babaf754d118c9d013cbc72a9aefee8d44/R/functions.R#L129

**Comment by AndreaPi** [comment]
Thanks a lot! That was quick 😃

**Comment by elinw** [comment]
Should we try to document that in the vignette?
