### ISSUE TITLE
Suggestion - use HTML entities for histograms in kable.skim_df

### ISSUE THREAD

**Issue by martinmodrak** [ropenscilabs/skimr#278]
I had encountered an instance of #54. Histograms showed up fine when displaying in RStudio notebook (on Windows), but break when using blogdown. In blogdown, the histogram characters get converted to (literally) things like ```<U+2583>```. This was problem with both direct rendering and rendering through ```kable```

I was able to get around by changing the characters in histograms to their corresponding HTML entities. No change of font/locale needed then. (I am not sure if it is easy to change the locale for blogdown environment, I found #54 only after I had this workaround).
````
 ```{r results='asis'}
skimmed <- cars %>% skim() 
skimmed_better <- skimmed %>% rowwise() %>%  mutate(formatted = 
     if_else(stat == "hist", 
         utf8ToInt(formatted) %>% as.character() %>% paste0("&#", . ,";", collapse = ""), 
         formatted))  
mostattributes(skimmed_better) = attributes(skimmed)

skimmed_better %>% kable(escape = FALSE)
 ```
````

I think it might be good idea to have ```kable.skim_df``` output HTML entities for special characters in HTML output. If you agree, I can try to write a pull request with this.

**Comment by elinw** [comment]
This is a really neat idea.  It also aligns with my thinking that we need in general to improve the html of the outputs.  @michaelquinn32  Please take a look at this way to address some of the issues with rendering.  
A pull request would be welcome, would you want to take a look at linegraphs also? They use the braille characters.

**Comment by martinmodrak** [comment]
So I had a go on this and it turns out, it requires some hacking around the default escaping mechanism of knitr. Which led me to believe that the conversion to entities might be better placed in knitr proper. I filed an issue there (https://github.com/yihui/knitr/issues/1506) and will let you know once that proceeds.

**Comment by elinw** [comment]
Hm read the discussion on that issue, discouraging. This is interesting https://stackoverflow.com/questions/13018570/convert-character-to-html-in-r.
I'm somewhat surprised that there is not a good a well established way to do this.

**Comment by jfsalzmann** [comment]
@martinmodrak @elinw I know this thread is dead, just want to note I ran into a similar issue but with PDF output - doesnt seem to be possible at all to use UTF8 characters for histogram plotting within Latex (as long as pdflatex is used, since these characters do not exist in the typesetting font). 

Would be awesome to have an option for using Skimr in RMarkdown HTML/Latex contexts.

**Comment by elinw** [comment]
It's crucial to use the right engine for the PDFs.  In the end we will have to consider how far we can go to fix pdfs and html since the original vision of skimr was for in the console. I'd go a fair way but at some point it then becomes a package about rendering.
