### ISSUE TITLE
Add counts of Inf,-Inf and NaN in data

### ISSUE THREAD

**Issue by elinw** [ropenscilabs/skimr#281]
We count NAs but it might make sense to report these also.

**Comment by elinw** [comment]
NaNs are getting counted in the missing column already so that leaves the question of either counting or saying if there are any Inf or -Inf values.

**Comment by elinw** [comment]
My thinking right now is that we could add a warning to inline_hist. Currently for mean and p100 the result will be Inf (or p0 -Inf) the user would see it, but if those have been changed they would not know about the treatment in the histogram.

**Comment by elinw** [comment]
@jenniferthompson I implemented this in the current pull request. So if there are Inf values, they are handled normally for most statistics (such as returning Inf for mean and NA for sd) but for inline_hist we are now converting them to NA and then (once the PR is merged) will issue a warning.

**Comment by jenniferthompson** [comment]
That sounds great @elinw! :clap:

**Comment by elinw** [comment]
Fixed in master.
