### ISSUE TITLE
Add variable descriptions and turn skimr-output into data dictionary

### ISSUE THREAD

**Issue by henningsway** [ropenscilabs/skimr#284]
I am just discovering the functionality of skimr.

I thought it would be cool to find a convenient way to add explicit variable descriptions to the skimr-output, so that it can be used as a data dictionary.

Maybe this could be implemented with a custom statistic, based on the variable name and a lookup table.

(see https://github.com/dmrodz/dataMeta for an example for a data dictionary created with R)

**Comment by elinw** [comment]
That's an interesting thought possibly as an expanded part of summary().  Right now anyone could add a data description attribute to each column and then create a "statistic" that returns that value.  Overall I would say the basic (long) skim object  could be reshaped into what you are suggesting if  desired.  If this were a core feature of skimr how would it work?

**Comment by henningsway** [comment]
I thought about this for a little bit and I am not yet sure, what the right approach would be. Here are some of my thoughts.

- _I think semi-automatic data dictionary creation makes sense, because the variable-names and -types are already defined in the data, so I only have to add their description._
- maybe the entering of the description can be supported by a shiny-gadget or so (where I get the names and types and can enter the descriptions)
- the descriptions persisted as a `tribble()` and joined into the skimr-object
- the ability to export to excel would be nice, but html output should also be possible
- include an argument to turn the summary statistics on and off
- Name, Type, Descriptions, Summary Statistics would be the logical ordering of the result
- Maybe the data dictionary can be shared as an `html_notebook`, so the source of the document can be preserved and shared easily.

**Comment by elinw** [comment]
I think there are a few people working on similar ideas and it could be that skimr plays a part in them.  I'm going to  close this for now but when you come up with a specific issue related to what you are creating you can create a new issue.
