### ISSUE TITLE
Error in .f(.x[[i]], ...) :    Names missing from the following functions:  top_counts

### ISSUE THREAD

**Issue by PhilSmith26** [ropenscilabs/skimr#299]
I cannot get skim() to work on my data frame. summary() and str() both work fine, but skim() yields the message Error in .f(.x[[i]], ...) : 
  Names missing from the following functions:  top_counts
Any idea what's going on here?

Phil

> summary(d0)
       SubDate         Price           Quantity      
 30/01/2018:3862   Min.   : 2.000   Min.   :  0.025  
 31/01/2018:3251   1st Qu.: 5.000   1st Qu.:  3.500  
 25/01/2018:2528   Median : 6.430   Median : 14.000  
 26/01/2018:1849   Mean   : 6.816   Mean   : 20.248  
 01/02/2018:1571   3rd Qu.: 8.500   3rd Qu.: 28.000  
 02/02/2018: 727   Max.   :20.000   Max.   :400.000  
 (Other)   :2973                    NA's   :2906     
   Quality            City          Province   
       :  155   toronto : 1480   QC     :5101  
 High  :10223   montreal: 1461   ON     :4543  
 Low   :  387   calgary : 1140   AB     :2594  
 Medium: 5996   edmonton:  973   BC     :2254  
                ottawa  :  885   NS     : 645  
                quebec  :  659   MB     : 477  
                (Other) :10163   (Other):1147  
                 Reason            Frequency   
 Medical document   : 1715   Daily      :9074  
 Medical no document: 4336   Few a week :3154  
 Recreation         :10710   Few a month:1571  
                                        :1254  
                             Few a year :1113  
                             1          : 189  
                             (Other)    : 406  
  Consumption           Value         
 Min.   :  0.0001   Min.   :   0.107  
 1st Qu.:  3.5000   1st Qu.:  27.650  
 Median :  7.0000   Median :  84.980  
 Mean   : 15.8131   Mean   : 128.122  
 3rd Qu.: 28.0000   3rd Qu.: 168.000  
 Max.   :456.0000   Max.   :4500.000  
 NA's   :595        NA's   :2906      
> str(d0)
'data.frame':	16761 obs. of  10 variables:
 $ SubDate    : Factor w/ 21 levels "01/02/2018","02/02/2018",..: 15 15 15 15 15 15 15 15 15 15 ...
 $ Price      : num  2.41 3.08 13.39 11.16 3.95 ...
 $ Quantity   : num  NA 3.5 NA NA 3.5 100 NA 14 28 28 ...
 $ Quality    : Factor w/ 4 levels "","High","Low",..: 4 1 2 2 2 2 2 4 2 4 ...
 $ City       : Factor w/ 752 levels "105 mile post 2",..: 506 270 685 37 386 211 211 356 685 742 ...
 $ Province   : Factor w/ 13 levels "AB","BC","MB",..: 11 11 9 9 11 11 11 11 9 3 ...
 $ Reason     : Factor w/ 3 levels "Medical document",..: 3 3 1 1 3 3 3 3 3 3 ...
 $ Frequency  : Factor w/ 30 levels "","0.00001","0.0001",..: 1 27 27 27 27 27 1 29 27 27 ...
 $ Consumption: num  456 454 448 448 354 227 224 150 114 112 ...
 $ Value      : num  NA 10.8 NA NA 13.8 ...
> skim(d0)
Error in .f(.x[[i]], ...) : 
  Names missing from the following functions:  top_counts

**Comment by elinw** [comment]
Can you try to figure out if it is one specific factor that is causing the problem? You could try skimming one at a time to see if it is a specific one that fails and then run a table on that one so we an get a sense of what is in there? of course 752 levels is a lot, but no reason it should really cause problems.

**Comment by PhilSmith26** [comment]
I tried skim() for each of the ten columns in my data frame individually. It worked fine for 7 out of 10. The ones that did not work were City, Frequency and Quality.
> skim(d0$Quality)
Error in skim_v(.data) : 
  Names missing from the following functions:  top_counts
> skim(d0$Frequency)
Error in skim_v(.data) : 
  Names missing from the following functions:  top_counts
> skim(d0$Quality)
Error in skim_v(.data) : 
  Names missing from the following functions:  top_counts
All three are Factor class with some "" values.

Phil

**Comment by elinw** [comment]
I can't even get R to let me make a factor variable with "" values.    If I can find away to check for them I think it's probably not hard to do a workaround. 
Do you know how you ended up with those values?   How are you reading in that data?

**Comment by elinw** [comment]
Okay```

a <- c("a", "b", "b", "")
a <- as.factor(a)
skim(a)
```
Produces the error, due to  `urrr::set_names(as.integer(tab), names(tab))`,

**Comment by PhilSmith26** [comment]
My dataset is a csv file containing the results of an online survey. People who respond to the survey are asked to answer 10 questions, but they can skip some questions in which case the csv file contains a blank entry ("") for those questions.

**Comment by elinw** [comment]
Ok, actually elsewhere you can see we have a discussion about the empty character string issue. So I'm going to assume you have no control over this (although you could certainly consider doing StringsAsFactors = FALSE, and instead I think we should warn.  Since one purpose of skimr is to tell people what is in their data and then allow them to iteratively clean up the data we don't just want to ignore it.  Then the question is how to handle this in the actual skim.   I think we should convert these to " ".  But we could also convert to NA.  In your case it wouldn't matter but in other people's cases I guess it is possible there could already be NA values.

Anyway right now I'm thinking

```
sorted_count <- function(x) {
  tab <- table(x, useNA = "always")
  if (is.element("",  names(tab))) {
    tab[tab == ""] <- " "
    warning("Variable contains one or more values of \"\" that have 
            been converted to \" \". ") 
  }
  out <- rlang::set_names(as.integer(tab), names(tab))
  sort(out, decreasing = TRUE)
}
```

**Comment by PhilSmith26** [comment]
Thanks. It's a useful package and I will be using it a lot in future.

Philip

**Comment by elinw** [comment]
Not sure why you closed this, it is definitely a bug.  In your case to get it to run, you should  read in your csv file with StringsAsFactors=FALSE.  Then if you want those variables as factors _before_ using `as.factor()` convert the "" to NA or to " ".

**Comment by elinw** [comment]
https://github.com/ropenscilabs/skimr/pull/300

**Comment by elinw** [comment]
Fixed in master
