### ISSUE TITLE
allow wide data frame version to be extracted

### ISSUE THREAD

**Issue by rubenarslan** [ropenscilabs/skimr#303]
I'd like to be able to merge the printed wide version of the skimmed df (that is generated in skim_print) on some other information about those variables (for [this codebook package](github.com/rubenarslan/codebook)). 
Currently, to do so, I'd need to work with internal functions if I understand correctly.

**Comment by elinw** [comment]
I'm not sure what you mean.  print.skim_df() generates a separate data frame of formatted (character) data for each type not a single data frame that you could merge.   You can use `skim_to_wide()` to get a single wide data frame of formatted values with the not not applicable statistics for each type treated as NA.  `skim_to_list()` will five you the data frames separated by type.  Also, you can work with the long  skim_df object  to do whatever you want including adding new rows.

**Comment by rubenarslan** [comment]
Very sorry, I was on an old version. I thought I'd updated very recently, must have been on a different machine. `skim_to_wide()` is exactly what I want.
