### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/skimr#324]
Could skimr maintainers please make sure to git tag each CRAN release https://github.com/ropenscilabs/skimr/tags and plop in associated NEWS items for that release - thanks! e.g., https://github.com/ropensci/taxize/releases/tag/v0.9.3

**Comment by elinw** [comment]
We actually have been doing news for each release, but we keep forgetting to change the date when we the release. Yes I realize I forgot to tag though!

**Comment by sckott** [comment]
okay, thanks

**Comment by elinw** [comment]
Okay done. Thanks for pointing that out.
