### ISSUE TITLE
Minor code error in skim documentation

### ISSUE THREAD

**Issue by jmcurran** [ropenscilabs/skimr#333]
This line (about Unicode encoding and where to get help)

`vignette("Using_skimr" package = "skimr")`

should read

`vignette("Using_skimr", package = "skimr")`

**Comment by elinw** [comment]
Where is that?

**Comment by jmcurran** [comment]
Sorry, in the help file for `skim` under the header Unicode Rendering

**Comment by elinw** [comment]
Great thanks.
