### ISSUE TITLE
release notes?

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/skimr#340]
Could you include all relevant news items for each release notes set in your releases tab?  Looks like you have for some older releases, but not for the latest one

thanks!

**Comment by elinw** [comment]
I think we included everything?  This was a quick release (under a month since the last one) because the CRAN team found a typo in one of our tests.

**Comment by sckott** [comment]
hugh, when i looked at https://github.com/ropenscilabs/skimr/releases/tag/1.0.3 i don't remember seeing all that, anyway, that looks good, matching what's in news https://cran.rstudio.com/web/packages/skimr/news/news.html  - thanks again

**Comment by elinw** [comment]
Ok good.
