### ISSUE TITLE
Default vector method

### ISSUE THREAD

**Issue by AmeliaMN** [ropenscilabs/skimr#49]
Right now, `skim(mtcars$mpg)` fails with `Error in UseMethod("skim") :
 no applicable method for 'skim' applied to an object of class "c('double', 'numeric')"`. `skim_v()` solves the issue but we should do something better by default. Better error message? Use `skim_v()`?

**Comment by elinw** [comment]
I think this issue (couldn't handle columns with two classes) is fixed.

**Comment by elinw** [comment]
This is the same issue as in diamonds ... right now the latest commits by @michaelquinn32 should fix in this case since double and numeric are treated the same so the fall back to numeric is okay.

**Comment by elinw** [comment]
This is fixed in master.
