### ISSUE TITLE
Support select verbs within the function?

### ISSUE THREAD

**Issue by michaelquinn32** [ropenscilabs/skimr#5]
One approach to writing skim piplines keeps us away from having to reimplement dplyr tools. For example:

```
select(mtcars, cyl) %>%
  skim()
```

Alternatively, we might be interested in allowing for column selection within `skim()`.

```
skim(mtcars, cyl)
```

The latter approach gets us closer to the API listed in Amelia's original issue.

**Comment by michaelquinn32** [comment]
Similarly, do we want to open up our own select methods? What if I only want the numeric columns.

```
skim_if(is.numeric)
```

**Comment by elinw** [comment]
This I think is at least largely  accomplished with the tidyselect addition.
