### ISSUE TITLE
skimr pkg - same error message for any dataframe

### ISSUE THREAD

**Issue by sfd99** [ropenscilabs/skimr#56]
Installed colformat and skimr pkgs,
as indicated in GitHub pg. Ok!

> **skim(chickwts)**  # or any other data frame (ie: mtcars, iris...)
   _returns this message_:
      "Error in overscope_eval_next(overscope, expr) : object 'level' not found"

_**Using**_:
 - latest Rstudio v.1.0.143
 - R 3.4.0 (latest R)
 - **Ubuntu Linux** (32 bit)
 - dplyr 0.5.0  - installed from tidyverse dev pkg version: **1.1.1.9000**, (not from CRAN).
 - tibble 1.3.1
   ...and all other latest pkgs.

Thanks for any guidance-
...skimr looks VERY useful, eager to use it in **Rstudio / Linux** :-)

**Comment by elinw** [comment]
When you say latest version do you mean the latest from CRAN or the development versions on github? I can see that tidytesx uses overscope/

**Comment by sfd99** [comment]
As I said before (see my post above),
dplyr 0.5.0.9001 (= from **tidyverse development pkg**).

**Comment by elinw** [comment]
Well it's less than a week old so yeah I'd say still beta.  I think this is an error coming from tidytext but maybe we can get that fixed.

**Comment by sfd99** [comment]
_**Great, Elinw!**_
Thanks for answering 
and fixing this for us, _**Linux** users_...

Really eager to use **skimr** (in **Linux** 32bit / **Rstudio** latest version...).

**Comment by elinw** [comment]
Can you try running `skim_v(iris$Petal.Length)`? 
Also can you show me a traceback?

**Comment by elinw** [comment]
@sfd99 Any chance pf getting a traceback?

**Comment by sfd99** [comment]
**@elinw** : sorry for the delay.
skimr WORKING OK now!
(latest Rstudio w/R 3.4.0 in Ubuntu Linux 32-bit).
Thanks!
**PS:**    Yes - simple, clear examples 
           for each skimr function urgently needed...
**PS2:**  Q: How to fit skim(mtcars) output 
                  in one line?. 
                  reason for Q:  On my 19" monitor,
                  each var line "wraps" into 2 lines.
                  It gets confusing and hard to read the "wrapped" info for all variables....

**Comment by elinw** [comment]
I think this is tibble at work, what you can do is set the width to Inf.
From the [tibble docs](https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html).

> You can control the default appearance with options:
> 
> options(tibble.print_max = n, tibble.print_min = m): if there are more than n rows, print only the first m rows. Use options(tibble.print_max = Inf) to always show all rows.
> 
> options(tibble.width = Inf) will always print all columns, regardless of the width of the screen.
> 
> 

Still would you mind starting that as a separate issue? I think it's important.
