### ISSUE TITLE
Error in .summary_functions[[type]] :    wrong arguments for subsetting an environment 

### ISSUE THREAD

**Issue by bdornan1** [ropenscilabs/skimr#59]
Time series data, unbalanced

str(data_complete_raw)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	2448 obs. of  37 variables:
 $ iso                : chr  "AUS" "AUS" "AUS" "AUS" ...
 $ Country            : chr  "Australia" "Australia" "Australia" "Australia" ...
 $ Year               : POSIXct, format: "1870-01-01" "1871-01-01" "1872-01-01" "1873-01-01" ...
 $ before.indepence   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ currency.crises    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ inflation.crises   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ stock.crash        : num  0 0 0 0 0 0 0 0 0 0 ...
 $ sov.debt.crises.dom: num  0 0 0 0 0 0 0 0 0 0 ...
![skimr](https://cloud.githubusercontent.com/assets/7958543/26528509/a3ab514e-437b-11e7-8ea8-5314a20edff4.PNG)

**Comment by elinw** [comment]
https://github.com/ropenscilabs/skimr/pull/73

**Comment by elinw** [comment]
Same issue as https://github.com/ropenscilabs/skimr/issues/67

**Comment by elinw** [comment]
This should work with the current version since POSIXct support is added.
