### ISSUE TITLE
fail to install on mac

### ISSUE THREAD

**Issue by vidyasagarbhargava** [ropenscilabs/skimr#65]
Hi
I was unable to install skimr on mac using below command.
install_github("ropenscilabs/skimr")

Thanks

**Comment by mattbk** [comment]
Do you have `devtools` installed? What is the error message you get?

**Comment by elinw** [comment]
@vidyasagarbhargava  Can you provide any additional information?

**Comment by vidyasagarbhargava** [comment]
Hi,
Yes, I have devtools installed. I have tried installing it today and it's successful this time.

Thanks

**Comment by elinw** [comment]
Great
