### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by dsdesrosiers** [ropenscilabs/skimr#66]
Gerring error....

Error in nchar(x) : invalid multibyte string, element 11 

Is it possible to return the name of the column that is causing the issue?

**Comment by michaelquinn32** [comment]
Hi!

Would you mind pointing us to a data frame that throws this mysterious error message? Or even better, could you share a code snippet that consistently generates the error?

Thanks!

**Comment by elinw** [comment]
@dsdesrosiers Hi, It's been close to 2 months since we asked for more information.  I'm going to close the issue at this point, but if you do have an example just post here and I'll reopen this.

**Comment by dsdesrosiers** [comment]
@elinw - I apologize for such a poor response. I have loaded the current dev version and at the moment cannot reproduce the problem. I tested with the mtcars data as well as three different frames of my own data without issue. now that it's working for me I love it :-)
