### ISSUE TITLE
Organizing the output of the function

### ISSUE THREAD

**Issue by michaelquinn32** [ropenscilabs/skimr#7]
The example from precis is organized a lot like the output of `str()` or `dplyr::glimpse()`. We don't have to adhere to this format if we don't want to.

If we have lots of variables, do we want grouped output from `print.skim()`. Here is one suggestion:

```
# Skim of a My data frame
# META Stats Nvariables N obs

## Numeric Variables
#> x missing: mean: median: sd: ...

## Categorical (factors or character vectors? Separate?)
#> c missing: level_a: level_b: ...
```

**Comment by elinw** [comment]
I'm going to close since we seem to have adopted a model close to this. If we want to revise that let's do it as a new discussion.
