### ISSUE TITLE
stat=="hist" does not show

### ISSUE THREAD

**Issue by Kucharssim** [ropenscilabs/skimr#74]
Hi, I tried the skim function with the piped filter, but the histogram is not showed:

![image](https://cloud.githubusercontent.com/assets/7093546/26754264/8e97695e-4877-11e7-9f55-b6c3bd975a5b.png)

My R version:
![image](https://cloud.githubusercontent.com/assets/7093546/26754274/a6d95432-4877-11e7-8fe8-0bb3cfba7db7.png)

Thanks for nice idea!
Simon

**Comment by elinw** [comment]
https://github.com/ropenscilabs/skimr/issues/54

**Comment by elinw** [comment]
Can you please post sessionInfo()?

**Comment by Kucharssim** [comment]
![image](https://cloud.githubusercontent.com/assets/7093546/26801234/81ef801c-4a3c-11e7-8cee-0f6624843926.png)

**Comment by elinw** [comment]
Information merged.
