### ISSUE TITLE
Output of skim.grouped_df()

### ISSUE THREAD

**Issue by GShotwell** [ropenscilabs/skimr#82]
There's an open question of what the skim output should be for grouped dataframes. In my view we should match the `dplyr::summarize()` behaviour and display the grouping variables in the leading columns and preserve the grouping values in the skim_df. Currently I have the function behaving like this: 

```
mtcars %>% 
  group_by(cyl, gear) %>% 
  skim() %>% 
  .[1:10,] %>% 
  knitr::kable()
```

| cyl| gear|var |type    |stat     |level |     value|
|---:|----:|:---|:-------|:--------|:-----|---------:|
|   6|    4|mpg |numeric |missing  |.all  |  0.000000|
|   6|    4|mpg |numeric |complete |.all  |  4.000000|
|   6|    4|mpg |numeric |n        |.all  |  4.000000|
|   6|    4|mpg |numeric |mean     |.all  | 19.750000|
|   6|    4|mpg |numeric |sd       |.all  |  1.552418|
|   6|    4|mpg |numeric |min      |.all  | 17.800000|
|   6|    4|mpg |numeric |median   |.all  | 20.100000|
|   6|    4|mpg |numeric |quantile |25%   | 18.850000|
|   6|    4|mpg |numeric |quantile |75%   | 21.000000|
|   6|    4|mpg |numeric |max      |.all  | 21.000000|

**Comment by elinw** [comment]
How would you make it possible to script it if the column names change depending on the variables and the number of variables would vary.  For example, maybe we would bring over the Groups attribute.

**Comment by GShotwell** [comment]
I'm having trouble grokking this one, do you have an example I could work
off of?

**Comment by elinw** [comment]
Well if you do 
 ```
x<-dplyr::group_by(iris, Species)
str(x)
dplyr::groups(x)
```
So if we bring over the output of groups someone could use that to loop through the column names.

**Comment by GShotwell** [comment]
Currently the output of `groups(skim(df))` is the same as `groups(df)` does
that cover it?

**Comment by elinw** [comment]
Great! Bad on me for not checking.
So we know the groups and how many there are.

**Comment by elinw** [comment]
I think this looks good. We'd just need to work out the custom printing, e.g. would each group get a separate tibble? I think that's probably the way to go.

**Comment by elinw** [comment]
I'm going to merge this wtih https://github.com/ropenscilabs/skimr/issues/53  I think we're in good shape and can put the discussion in one place.
