### ISSUE TITLE
Make histogram optional

### ISSUE THREAD

**Issue by GShotwell** [ropenscilabs/skimr#83]
@haozhu233  and I did a bit of benchmarking of `skim()` and it looks like there are some performance issues with drawing the histogram. This is evident on large grouped data frames. We might want allow the user to not draw the histograms if they are interested in speedier skimming.

**Comment by elinw** [comment]
Maybe set_functions should take take newfuns with a negative sign to indicate removing.

**Comment by elinw** [comment]
What do you think about adding a remove parameter to skim_with()?

**Comment by elinw** [comment]
Or maybe even better, what about skim_without()?

**Comment by michaelquinn32** [comment]
skim_with(numeric = list(hist = NULL)) removes the histogram for all following calls of skim.

I'll add this as an example in skim_with() and add a test as well.
