### ISSUE TITLE
`skim` doesn't work with custom numeric function

### ISSUE THREAD

**Issue by tonyfischetti** [ropenscilabs/skimr#87]
Here's a simple reproducible example:

```
library(dplyr)
library(skimr)

skim_with(numeric=list(mn=purrr::partial(mean, na.rm=TRUE)), append=FALSE)
iris %>% skim
```
yields:
```
Error in enc2utf8(col_names(col_labels, sep = sep)) :
  argument is not a character vector
```

Something is `skim_print.R` seems to be interfering with this working properly. Does `format_num` rely on the default function being there?

**Comment by GShotwell** [comment]
Thanks for the great example. This is a problem with the print method but
```
skim_with(numeric=list(mn=purrr::partial(mean, na.rm=TRUE)), append=FALSE)
 test <- iris %>% skim
```
works fine. 


It looks like the offending code is this bit of `formatnum`  which expects a histogram value: 

```
  tmp2 <- dplyr::mutate(dplyr::filter(x, stat == "hist"), value = level)
  tmp2 <- tidyr::spread(dplyr::select(tmp2, -level), stat, value)

```

Probably we should refactor the print method to not expect the default `skim` functions, but I'm going to hold off fixing it because I think the `print` method is still in flux.

**Comment by elinw** [comment]
One thing is that is not inherently obvious to people that the skim object is different from the print.skim rendering.    I'd kind of like to have a method that would print the long version, but right now you can see it by doing as.data.frame(skim(dfname)). 

@michaelquinn32 and I were discussing print in another issue. https://github.com/ropenscilabs/skimr/issues/71
https://github.com/ropenscilabs/skimr/pull/72

**Comment by tonyfischetti** [comment]
Ok, cool! Yeah, I'm heavily in favor of the print method not needed the default methods :)

**Comment by elinw** [comment]
Here's a refactor of skim_print() which I think would address the issue.
https://github.com/ropenscilabs/skimr/pull/101

**Comment by elinw** [comment]
I believe this specific issue is resolved thanks to other changes.
