### ISSUE TITLE
Deal with complex numbers

### ISSUE THREAD

**Issue by AmeliaMN** [ropenscilabs/skimr#9]
What summary statistics do people who work with complex numbers want? Is `mean()` meaningful?

**Comment by elinw** [comment]
Started with a few stats but we're limited by the value column being numeric.

**Comment by elinw** [comment]
We now have basic support, but if people want other stats that can work in the numeric column they could be added to this issue.

**Comment by elinw** [comment]
I'm actually going to close since we now  have the basic support and when people have PRs or other requests they can open new issues.
